telegram_dbt: # Your dbt project name
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost # Or your dev DB host
      port: 5432
      user: "{{ env_var('PGUSER') }}"
      password: "{{ env_var('PGPASSWORD') }}"
      dbname: "{{ env_var('PGDATABASE') }}"
      schema: public # Or your dev schema
      threads: 1
    ci: # New profile for CI
      type: postgres
      host: localhost # Connects to the service set up by setup-postgres
      port: 5432
      user: "{{ env_var('PGUSER') }}"
      password: "{{ env_var('PGPASSWORD') }}"
      dbname: "{{ env_var('PGDATABASE') }}"
      schema: public # Or your CI schema
      threads: 1