version: 2

models:
  - name: stg_telegram_messages
    description: "Staging model that cleans raw telegram messages."
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: channel
        tests:
          - not_null

  - name: dim_channels
    description: "Dimension table for Telegram channels."
    columns:
      - name: channel
        tests:
          - unique
          - not_null

  - name: dim_dates
    description: "Dimension table for dates."
    columns:
      - name: date_key
        tests:
          - unique
          - not_null

  - name: fct_messages
    description: "Fact table containing message metrics and foreign keys."
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
      - name: channel_key
        tests:
          - not_null
      - name: date_key
        tests:
          - not_null

tests:
  - name: no_future_dates
    description: "Ensure no messages are dated in the future."
    test_sql: |
      select * from {{ ref('fct_messages') }}
      where date_key > current_date
