version: 2

models:
  - name: stg_telegram_messages
    description: "Staging model that cleans raw telegram messages."
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: text
        tests:
          - not_null:
              where: "has_media = true AND is_image = false"
      - name: has_media
        tests:
          - not_null

  - name: dim_channels
    description: "Dimension table for Telegram channels."
    columns:
      - name: channel
        tests:
          - unique
          - not_null

  - name: dim_dates
    description: "Dimension table for dates."
    columns:
      - name: date_key
        tests:
          - unique
          - not_null

  - name: fct_messages
    description: "Fact table containing message metrics and foreign keys."
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
      - name: channel_key
        tests:
          - not_null
      - name: date_key
        tests:
          - not_null
  - name: fct_image_detections
    description: "Fact table for storing YOLOv8 object detections from Telegram images."
    columns:
      - name: message_id
        description: "Foreign key to fct_messages.message_id"
        tests:
          - not_null
      - name: detected_object_class
        description: "Name of the object class detected by YOLOv8"
        tests:
          - not_null
      - name: confidence_score
        description: "Confidence score for the detected object"
        tests:
          - not_null


